name: "Test and Lint"

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: setup Node.js
        uses: actions/setup-node@v3.1.1
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn

      - name: eslint review
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          eslint_flags: './**/*.{ts,tsx,js,jsx}'

      - name: Run eslint
        run: yarn lint

      - name: Run Jest
        run: yarn test --coverage

      - name: Compile Typescript
        run: yarn check-types

      - name: Show coverage in comments
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          package-manager: 'yarn'
          test-script: "yarn run test -- --coverage --silent --testLocationInResults --ci --json --outputFile=\"report.json\""
